repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: 4.11.2
  values:
    - controller:
        replicaCount: 3
        service:
          type: LoadBalancer
- name: prometheus
  namespace: prometheus
  chart: prometheus-community/prometheus
  set:
  - name: rbac.create
    value: false
- name: postgresql
  namespace: postgresql
  chart: bitnami/postgresql
  values:
    - auth:
        username: secret-user
        password: secret-password